version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bank-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banking_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: bank-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # Прописываем путь к базе внутри сети Docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/banking_api
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data: